"""add device commands and last seen

Revision ID: d79a21f03fa0
Revises: 789e2522013f
Create Date: 2026-08-30 18:12:20.157132

Database foundation for the approved outbound-only ESP32 command
architecture (app.models.device_command.DeviceCommand): the backend
never calls the device directly — the ESP32 polls for pending commands
on its own outbound HTTPS cycle, applies them locally through firmware
safety logic, then reports back what actually happened. No routes or
services are added by this migration; it is schema only.

Autogenerated from DeviceCommand and Device.last_seen_at; no columns,
constraints, or indexes beyond what those models declare are introduced
here. Neither new foreign key (device_commands.device_id,
device_commands.requested_by_user_id) carries ON DELETE CASCADE — a
command row is a historical audit record worth preserving even if its
device or user is later removed, so deleting either while command rows
reference it is left to the database's default RESTRICT behavior. See
DeviceCommand's own docstring for the full field-by-field reasoning.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd79a21f03fa0'
down_revision: Union[str, Sequence[str], None] = '789e2522013f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('command_type', sa.String(length=20), nullable=False),
    sa.Column('requested_pump_state', sa.Boolean(), nullable=True),
    sa.Column('requested_manual_override', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('applied_pump_state', sa.Boolean(), nullable=True),
    sa.Column('applied_manual_override', sa.Boolean(), nullable=True),
    sa.Column('was_safety_refused', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_commands_device_id'), 'device_commands', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_commands_id'), 'device_commands', ['id'], unique=False)
    op.create_index(op.f('ix_device_commands_requested_by_user_id'), 'device_commands', ['requested_by_user_id'], unique=False)
    op.add_column('devices', sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'last_seen_at')
    op.drop_index(op.f('ix_device_commands_requested_by_user_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_id'), table_name='device_commands')
    op.drop_index(op.f('ix_device_commands_device_id'), table_name='device_commands')
    op.drop_table('device_commands')
    # ### end Alembic commands ###
